### ISSUE TITLE
Error using the common endpoint

### ISSUE THREAD

**Issue by colinrippeyfinarne** [BobGerman/AADsamples#3]
I'm running through the 30 days of graph series. I've downloaded and configured the various files as per the instructions, I am at the stage of running http-server and then opening my browser (using the http://127.0.0.1:8080 url).

I click the link for V2 Endpoint (Javascript) and I see a Sign In button. 
I click the Sign In button and popup appears.
I try to login
I get the following error message:

AADSTS50194: Application 'XXXXXXXX' is not configured as a multi-tenant application. Usage of the /common endpoint is not supported for such applications created after '10/15/2018'. Use a tenant-specific endpoint or configure the application to be multi-tenant.

Am I missing a step in the code somewhere? I note in the file index.2a.html on lines 39/40:

                //Pass null for default authority (https://login.microsoftonline.com/common)
            var myMSALObj = new Msal.UserAgentApplication(applicationConfig.clientID, null, acquireTokenRedirectCallBack,

Should this line be tweaked? Should I have configured the App Reg to be multi-tenant?

**Comment by colinrippeyfinarne** [comment]
I changed the line:

    var myMSALObj = new Msal.UserAgentApplication(applicationConfig.clientID, null, acquireTokenRedirectCallBack,

To use an explicit tenant:

    var myMSALObj = new Msal.UserAgentApplication(applicationConfig.clientID, "https://login.microsoftonline.com/<mytenant>.onmicrosoft.com", acquireTokenRedirectCallBack,

And it worked (well it worked after I changed the browser to use the url http://localhost:8080 and not http://127.0.0.1:8080 as I mentioned above as http://127.0.0.1:8080 was not one of the reply urls).

**Comment by BobGerman** [comment]
Hi @colinrippeyfinarne  - Glad you tried this and thanks for your interest!

The instructions should have been clear to use "localhost" and not an IP address. The reply URL has to match. Unfortunately, the errors returned are notoriously inaccurate and I've seen that same error for any number of possible issues. I think you'll find you can change the URL back to use common and it will work; this was well tested by at least 5 people prior to publication, and as noted in the blog article, it comes from a tutorial that was written by the Azure AD group: https://docs.microsoft.com/en-us/azure/active-directory/develop/tutorial-v2-javascript-spa

I hope this helps; thanks!

**Comment by colinrippeyfinarne** [comment]
Thanks for the response @BobGerman I'll close the issue now.
